allowBuilds:
  esbuild: true
  sharp: true

engineStrict: true

gitBranchLockfile: true

mergeGitBranchLockfilesBranchPattern:
  - main
  - release*

minimumReleaseAge: 0

patchedDependencies:
  vite: patches/vite.patch

shellEmulator: true

verifyDepsBeforeRun: install
