allowBuilds:
  esbuild: true
  sharp: true

engineStrict: true

gitBranchLockfile: true

mergeGitBranchLockfilesBranchPattern:
  - main
  - release*

minimumReleaseAge: 0

shellEmulator: true

verifyDepsBeforeRun: install
